set -g status off
#Easier prefix key
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

#More intuitive pane splitting
bind '\' split-window -h
bind '-' split-window -v
#Vim-like pane switching cuz im not bitch-made
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
